### ISSUE TITLE
SVG with styled attributes gets ignored

### ISSUE THREAD

**Issue by edwardsdesign** [liderman/gulp-css-str2base64#1]
When I try to encode a SVG with styled attributes the image is ignored. If I remove the svg's style tag the task runs as expected.

Here is an example of a simple svg with styled attributes that will not encode:

`.svg-with-style {
  background-image: url('data:image/svg+xml;base64,str2base64("<svg version="1.1" id="circles" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" width="320px" height="100px" viewBox="0 0 320 100" style="enable-background:new 0 0 320 100;" xml:space="preserve" preserveAspectRatio="xMinYMin meet" baseProfile="full"><style type="text/css">.st0{fill:#f00;} .st1{fill:#0f0;} .st2{fill:#00f;}</style><circle id="circle-03" class="st0" cx="50" cy="50" r="50"/><circle id="circle-02" class="st1" cx="160" cy="50" r="50"/><circle id="circle-01" class="st2" cx="270" cy="50" r="50"/></svg>")');`

Thanks for you work on this plugin. I use inline svg's in my css file almost exclusively and this plugin has come in very handy for older browsers that need svg's to be encoded.

**Comment by liderman** [comment]
@edwardsdesign, thanks for the errors found. Sorry it took so long fix!

**Comment by edwardsdesign** [comment]
This seems to be working as expected now, thank you for fixing it!
